language: php

php:
  - '7.1'
  - '7.2'
  - '7.3'

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  slack:
    rooms:
      - secure: YtgpLyqu4Xu9U2Dl84mhhiDb1MC+CvYXaN6C7ycVRewydvjpAg4pFBFI5Gl+Xk9efG0FMOND1K73YjVot9dohmWkyjbYvTH8jfGrXKMwN8K4u709z180hzDUYbJ/GoY0Jqg21HjPhXrtqoUp+GzE63eJ+NGrvd+1xvIkRkuoeS3mhHpJnb1MoJz+BoynYLyTTQHgj3kDYo95G6lY3oUJGtHYfVe0awYzzitXXgTEerVXMv7rzKUnHXplKg60cF/itRVcDcIEl+VJQxhEuznVUKKSLbcTGt5DGA1z7xfLteshP0qa6dkLM9U3JsFfITqx9TrSO128g0L8d1ocRKJ+1H2a+vA6B+REft4iWymJHo69obMK1/3vyaHOasak9/+PkmI/tQmbVbUjhKPgCa9dGu+arBVm+0gAjLdILTPA8FjOT6c8IH5J1UmSeAbsWBKhbutThy2wWBThN8ewxgCTUIXCRo0HkT8+U4eDnMIIbLRB5OQyUhDG2YgU3uwXGcJ80YJ2TwTpmmVTHq8c6u6k27mDRz27LgGYyt8+kgW0pBXBqxE0okfYgAQ+KKUBE1BcSmDLQNY7aTLyQOU3KudixsaklmCVkaeazXsWVmfF5/O77iDYPwjeCcQKQusW/U7GIqTwDNaTL51M/mnPpVr3JdGrqTxcslu4aZyPVN2lxlo=
    on_success: change
    on_failure: always
